Admin.create(:name => 'admin', :email => 'admin@ncsu.edu', :password => 'a')
Project.create(:title => 'Project 1', :description => 'This is project 1',:burndown => [10,20,30],:btime => 3)
Project.create(:title => 'Project 2', :description => 'This is project 2',:burndown => [10,20,30],:btime => 3)
Developer.create(:name => 'dev1', :email => 'dev1@ncsu.edu', :password => 'd',:project_id => 1)
Developer.create(:name => 'dev2', :email => 'dev2@ncsu.edu', :password => 'd',:project_id => 2)
Story.create(:title => 'Story 1', :description => 'This is story 1', :project_id => 1, :stage => 'Analysis',:point_value => 100,:developer_id => 1)
Story.create(:title => 'Story 2', :description => 'This is story 2', :project_id => 1, :stage => 'Analysis',:point_value => 100,:developer_id => 1)
Story.create(:title => 'Story 3', :description => 'This is story 3', :project_id => 1, :stage => 'Analysis',:point_value => 100,:developer_id => 1)
Story.create(:title => 'Story 4', :description => 'This is story 4', :project_id => 2, :stage => 'Analysis',:point_value => 100,:developer_id => 2)
Story.create(:title => 'Story 5', :description => 'This is story 5', :project_id => 2, :stage => 'Analysis',:point_value => 100,:developer_id => 2)
Story.create(:title => 'Story 6', :description => 'This is story 6', :project_id => 2, :stage => 'Analysis',:point_value => 100,:developer_id => 2)